SET GLOBAL SQL_MODE = CONCAT(@@SQL_MODE, ',ONLY_FULL_GROUP_BY'); 

SELECT li.ID_J, SUM(li.QTY)
FROM SPJ li JOIN J j ON li.ID_J = j.ID_J
WHERE j.CITY = 'Athens'
GROUP BY li.ID_J
HAVING SUM(li.QTY) > 1000;
