SET GLOBAL SQL_MODE = CONCAT(@@SQL_MODE, ',ONLY_FULL_GROUP_BY'); 

SELECT ea.SSN1
FROM EstAmi ea
GROUP BY ea.SSN1
HAVING COUNT(*) < 3;

-- Variante :

SET GLOBAL SQL_MODE = CONCAT(@@SQL_MODE, ',ONLY_FULL_GROUP_BY'); 

SELECT p.Nom
FROM EstAmi ea JOIN Personne p ON ea.SSN1 = p.SSN
GROUP BY ea.SSN1, p.Nom
HAVING COUNT(*) < 3;
