SET GLOBAL SQL_MODE = CONCAT(@@SQL_MODE, ',ONLY_FULL_GROUP_BY'); 

SELECT DISTINCT li1.ID_S, li2.ID_S
FROM SPJ li1, SPJ li2
WHERE li1.ID_S < li2.ID_S
  AND li1.ID_P = li2.ID_P
  AND li1.QTY = li2.QTY;
