SET GLOBAL SQL_MODE = CONCAT(@@SQL_MODE, ',ONLY_FULL_GROUP_BY'); 

SELECT AVG(li.QTY), li.ID_S
FROM SPJ li JOIN S s ON li.ID_S = s.ID_S
WHERE s.CITY = 'London'
GROUP BY li.ID_S
HAVING SUM(li.QTY) > 800;
